# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Final(object):
    def setupUi(self, Final):
        Final.setObjectName("Final")
        Final.resize(447, 338)
        self.wdg_final = QtWidgets.QWidget(Final)
        self.wdg_final.setGeometry(QtCore.QRect(20, 20, 401, 291))
        self.wdg_final.setStyleSheet("QWidget #wdg_final {\n"
"background-color: qlineargradient(spread:pad, x1:0.994, y1:0.0793636, x2:1, y2:1, stop:0 rgba(255, 148, 150, 255), stop:0.681818 rgba(255, 183, 255, 253));\n"
"border-top-left-radius:50px;\n"
"border-bottom-right-radius:50px;\n"
"border-bottom-left-radius:15px;\n"
"border-top-right-radius:15px;\n"
"}")
        self.wdg_final.setObjectName("wdg_final")
        self.lbl_final = QtWidgets.QLabel(self.wdg_final)
        self.lbl_final.setGeometry(QtCore.QRect(-10, 20, 411, 71))
        self.lbl_final.setStyleSheet("color: #FFF;\n"
"font: 700 25pt \"Segoe Print\";\n"
"")
        self.lbl_final.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_final.setObjectName("lbl_final")
        self.btn_cerrar = QtWidgets.QPushButton(self.wdg_final)
        self.btn_cerrar.setGeometry(QtCore.QRect(360, 10, 31, 21))
        self.btn_cerrar.setStyleSheet("QPushButton {\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font: 700 18pt \"Segoe Print\";\n"
"color: rgb(107, 107, 107);}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    color: rgb(203, 203, 203);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(48, 48, 48);\n"
"}\n"
"")
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.label = QtWidgets.QLabel(self.wdg_final)
        self.label.setGeometry(QtCore.QRect(70, 80, 239, 209))
        self.label.setMinimumSize(QtCore.QSize(239, 209))
        self.label.setMaximumSize(QtCore.QSize(236, 209))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.setPixmap(QtGui.QPixmap(":/imagenes/corazon.png"))
        self.label.setScaledContents(True)

        self.retranslateUi(Final)
        QtCore.QMetaObject.connectSlotsByName(Final)

    def retranslateUi(self, Final):
        _translate = QtCore.QCoreApplication.translate
        Final.setWindowTitle(_translate("Final", "Form"))
        self.lbl_final.setText(_translate("Final", "¡Ahora somos novios!"))
        self.btn_cerrar.setText(_translate("Final", "X"))
