# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Game(object):
    def setupUi(self, Game):
        Game.setObjectName("Game")
        Game.resize(463, 331)
        Game.setStyleSheet("")
        self.wdg_widget_principal = QtWidgets.QWidget(Game)
        self.wdg_widget_principal.setStyleSheet("")
        self.wdg_widget_principal.setObjectName("wdg_widget_principal")
        self.wdg_game = QtWidgets.QWidget(self.wdg_widget_principal)
        self.wdg_game.setGeometry(QtCore.QRect(30, 20, 401, 291))
        self.wdg_game.setStyleSheet("QWidget #wdg_game {\n"
"background-color: qlineargradient(spread:pad, x1:0.994, y1:0.0793636, x2:1, y2:1, stop:0 rgba(255, 148, 150, 255), stop:0.681818 rgba(255, 183, 255, 253));\n"
"border-top-left-radius:50px;\n"
"border-bottom-right-radius:50px;\n"
"border-bottom-left-radius:15px;\n"
"border-top-right-radius:15px;\n"
"}")
        self.wdg_game.setObjectName("wdg_game")
        self.lbl_game = QtWidgets.QLabel(self.wdg_game)
        self.lbl_game.setGeometry(QtCore.QRect(130, 0, 111, 41))
        self.lbl_game.setStyleSheet("color: #FFF;\n"
"font: 700 25pt \"Segoe Print\";\n"
"")
        self.lbl_game.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_game.setObjectName("lbl_game")
        self.btn_iniciar = QtWidgets.QPushButton(self.wdg_game)
        self.btn_iniciar.setGeometry(QtCore.QRect(120, 240, 131, 41))
        self.btn_iniciar.setStyleSheet("QPushButton  {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font: 700 20pt \"Segoe Script\";\n"
"    \n"
"    \n"
"    background-color: rgb(255, 161, 163);\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgba(255, 131, 133, 0.7);\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(230, 72, 75);\n"
"    border-radius:10px;\n"
"}")
        self.btn_iniciar.setObjectName("btn_iniciar")
        self.btn_cerrar = QtWidgets.QPushButton(self.wdg_game)
        self.btn_cerrar.setGeometry(QtCore.QRect(360, 10, 31, 21))
        self.btn_cerrar.setStyleSheet("QPushButton {\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font: 700 18pt \"Segoe Print\";\n"
"color: rgb(107, 107, 107);}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    color: rgb(203, 203, 203);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(48, 48, 48);\n"
"}\n"
"")
        self.btn_cerrar.setObjectName("btn_cerrar")
        Game.setCentralWidget(self.wdg_widget_principal)

        self.retranslateUi(Game)
        QtCore.QMetaObject.connectSlotsByName(Game)

    def retranslateUi(self, Game):
        _translate = QtCore.QCoreApplication.translate
        Game.setWindowTitle(_translate("Game", "MainWindow"))
        self.lbl_game.setText(_translate("Game", "GAME"))
        self.btn_iniciar.setText(_translate("Game", "Iniciar"))
        self.btn_cerrar.setText(_translate("Game", "X"))
