# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Game_principal(object):
    def setupUi(self, Game_principal):
        Game_principal.setObjectName("Game_principal")
        Game_principal.resize(712, 467)
        self.wdg_principal = QtWidgets.QWidget(Game_principal)
        self.wdg_principal.setGeometry(QtCore.QRect(10, 10, 701, 431))
        self.wdg_principal.setStyleSheet("QWidget #wdg_principal {\n"
"background-color: qlineargradient(spread:pad, x1:0.994, y1:0.0793636, x2:1, y2:1, stop:0 rgba(255, 148, 150, 255), stop:0.681818 rgba(255, 183, 255, 253));\n"
"border-radius:15px;\n"
"}")
        self.wdg_principal.setObjectName("wdg_principal")
        self.btn_cerrar = QtWidgets.QPushButton(self.wdg_principal)
        self.btn_cerrar.setGeometry(QtCore.QRect(650, 10, 31, 21))
        self.btn_cerrar.setStyleSheet("QPushButton {\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font: 700 18pt \"Segoe Print\";\n"
"color: rgb(107, 107, 107);}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    color: rgb(203, 203, 203);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(48, 48, 48);\n"
"}\n"
"")
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.lbl_pregunta = QtWidgets.QLabel(self.wdg_principal)
        self.lbl_pregunta.setGeometry(QtCore.QRect(140, -20, 371, 41))
        self.lbl_pregunta.setStyleSheet("color: #FFF;\n"
"font: 700 25pt \"Segoe Print\";\n"
"")
        self.lbl_pregunta.setObjectName("lbl_pregunta")
        self.lbl_imagen = QtWidgets.QLabel(self.wdg_principal)
        self.lbl_imagen.setGeometry(QtCore.QRect(260, 190, 141, 121))
        self.lbl_imagen.setText("")
        self.lbl_imagen.setPixmap(QtGui.QPixmap(":/imagenes/corazon.png"))
        self.lbl_imagen.setScaledContents(True)
        self.lbl_imagen.setObjectName("lbl_imagen")
        self.btn_no = QtWidgets.QPushButton(self.wdg_principal)
        self.btn_no.setGeometry(QtCore.QRect(360, 330, 155, 42))
        self.btn_no.setStyleSheet("QPushButton  {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font: 700 20pt \"Segoe Script\";\n"
"    \n"
"    \n"
"    background-color:rgb(255, 144, 144);\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(255, 191, 165);\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"\n"
"    border-radius:10px;\n"
"}")
        self.btn_no.setObjectName("btn_no")
        self.btn_si = QtWidgets.QPushButton(self.wdg_principal)
        self.btn_si.setGeometry(QtCore.QRect(140, 330, 156, 42))
        self.btn_si.setStyleSheet("QPushButton  {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font: 700 20pt \"Segoe Script\";\n"
"    \n"
"    \n"
"    background-color: rgb(149, 255, 161);\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgba(213, 255, 234, 0.7);\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color:rgb(88, 231, 85);\n"
"    border-radius:10px;\n"
"}")
        self.btn_si.setObjectName("btn_si_2")

        self.retranslateUi(Game_principal)
        QtCore.QMetaObject.connectSlotsByName(Game_principal)

    def retranslateUi(self, Game_principal):
        _translate = QtCore.QCoreApplication.translate
        Game_principal.setWindowTitle(_translate("Game_principal", "Form"))
        self.btn_cerrar.setText(_translate("Game_principal", "X"))
        self.lbl_pregunta.setText(_translate("Game_principal", "¿Quieres ser mi novia?"))
        self.btn_no.setText(_translate("Game_principal", "No"))
        self.btn_si.setText(_translate("Game_principal", "Si"))
from game.images import images_rc
